pyspark 3.5.3
AnacondaRecipes/pyspark-feedstock pull request #8
Opened 2024-11-22 14:25 UTC by lorepirri

pyspark 3.5.3

**Destination channel:** defaults

### Links

- [PKG-6274]
- dev_url (pypi): https://github.com/apache/spark/tree/v3.5.3/python
- conda-forge: https://github.com/conda-forge/pyspark-feedstock/blob/main/recipe/meta.yaml
- pypi: https://pypi.org/project/pyspark/3.5.3
- pypi inspector: https://inspector.pypi.io/project/pyspark/3.5.3

### Explanation of changes:

- bump version

[PKG-6274]: https://anaconda.atlassian.net/browse/PKG-6274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-25 18:22 UTC, ViridianMelody requested changes

2024-11-25 18:22 UTC, ViridianMelody commented on recipe/meta.yaml
> +    - googleapis-common-protos >=1.56.4
```suggestion
  run_constrained:
    - grpcio >=1.56.0
    - grpcio-status >=1.56.0
    - googleapis-common-protos >=1.56.4
```
We haven't previously included the "connect" extras, so we can keep these in run_constrained.

2024-11-25 18:33 UTC, ViridianMelody approved these changes

2024-11-26 17:17 UTC, lorepirri commented on recipe/meta.yaml
>      # extras_require dependencies
```suggestion
    # extras_require dependencies are kept here
    # as runtime dependencies because previously
    # were set as such
```

2024-11-26 17:18 UTC, lorepirri commented on recipe/meta.yaml
> +    - grpcio >=1.56.0
```suggestion
    # We haven't previously included the "connect" extras, 
    # so we can keep these in run_constrained.
    - grpcio >=1.56.0
```

2024-11-26 17:18 UTC, lorepirri commented on recipe/meta.yaml
> +    - pyspark.sql
```suggestion
    - pyspark.sql
    # imports relative to connect are removed because is an extra
```

2024-11-26 17:21 UTC, ifitchet approved these changes
per-Slack: some comments to avoid repeated questions on choices.

Given that you're removing all the CI constructs, maybe we need to wait for @dbast's thoughts.  Someone might be relying on them.

2024-11-27 12:37 UTC, lorepirri commented
> per-Slack: some comments to avoid repeated questions on choices.
> 
> Given that you're removing all the CI constructs, maybe we need to wait for @dbast's thoughts. Someone might be relying on them.

I restored the CODEOWNERS, I think the CI is left over from conda-forge. I will wait for today for @dbast feedback on it.

2024-11-27 15:43 UTC, dbast commented
Feel free to merge this without my review. I only get pinged as I am part of the AnacondaRecipes Github Org and I am in the CODEOWNERS file due to being maintainer of the recipe in the upstream feedstock. The PR looks fine, the CI files can be wiped as the anaconda build system only cares about the recipe + local {cbc, abs}.yml files.

2024-11-27 16:47 UTC, lorepirri commented
> Feel free to merge this without my review. I only get pinged as I am part of the AnacondaRecipes Github Org and I am in the CODEOWNERS file due to being maintainer of the recipe in the upstream feedstock. The PR looks fine, the CI files can be wiped as the anaconda build system only cares about the recipe + local {cbc, abs}.yml files.

Thank you @dbast ! Will merge

2024-11-27 16:47 UTC, merged